video_segments = [
    {"url": "https://www.youtube.com/watch?v=OVU4i3z2Ie8", "start": "0:45", "end": "5:00"},
    {"url": "https://www.youtube.com/watch?v=KTKsNCjGDOc", "start": "0:15", "end": "3:15"},
    {"url": "https://www.youtube.com/watch?v=KXyK9CMHqjI", "start": "0:00", "end": "3:30"},
    {"url": "https://www.youtube.com/watch?v=8dDOfdol5Rc", "start": "0:20", "end": "4:20"},
    {"url": "https://www.youtube.com/watch?v=lC_gGTPzL9A", "start": "0:15", "end": "3:30"},
    {"url": "https://www.youtube.com/watch?v=KYjXbURtI40", "start": "0:05", "end": "3:30"},
    {"url": "https://www.youtube.com/watch?v=dJy4aSsGmqI", "start": "0:05", "end": "3:30"},
    {"url": "https://www.youtube.com/watch?v=zBlVMMwRbTI", "start": "0:00", "end": "3:00"},
    {"url": "https://www.youtube.com/watch?v=7LNtPYPJfoE", "start": "0:20", "end": "3:00"},
    {"url": "https://www.youtube.com/watch?v=GgyJZeLRjAo", "start": "0:00", "end": "3:30"},
    {"url": "https://www.youtube.com/watch?v=rKouu3A3lXI", "start": "0:03", "end": "4:00"},
    {"url": "https://www.youtube.com/watch?v=eC9cD9xdMwI", "start": "0:05", "end": "4:00"},
    {"url": "https://www.youtube.com/watch?v=bfq0syxer-c", "start": "0:05", "end": "3:30"},
    {"url": "https://www.youtube.com/watch?v=5Smhj6LudCU", "start": "0:05", "end": "4:00"},
    {"url": "https://www.youtube.com/watch?v=6b302I5b40I", "start": "0:00", "end": "3:00"},
    {"url": "https://www.youtube.com/watch?v=h_cOnJvp7WY", "start": "0:00", "end": "3:00"},
    {"url": "https://www.youtube.com/watch?v=lly9Tna1iQo", "start": "0:00", "end": "3:30"},
    {"url": "https://www.youtube.com/watch?v=w3uTDRfnyeQ", "start": "0:00", "end": "3:30"},
    {"url": "https://www.youtube.com/watch?v=IYs2ntywIO4", "start": "0:00", "end": "3:00"},
    {"url": "https://www.youtube.com/watch?v=itNAdqTWNaY", "start": "0:00", "end": "3:15"},
    {"url": "https://www.youtube.com/watch?v=Hr3qoTQjXKk", "start": "0:00", "end": "3:15"},
    {"url": "https://www.youtube.com/watch?v=VF8YFIbfowM", "start": "0:00", "end": "3:30"},
]

